"""baseline

Revision ID: 2c108307d4c2
Revises: 
Create Date: 2022-05-19 14:32:13.119368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c108307d4c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('contract_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('abi', mysql.JSON(), nullable=False),
    sa.Column('network_address', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('start_block_no', sa.Integer(), nullable=False),
    sa.Column('blocks_adjustment', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('network_address', name='uq_ct')
    )
    op.create_table('event',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('contract_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('event_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=False),
    sa.Column('transaction_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.row_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('transaction_hash', 'log_index', name='uq_evt')
    )
    op.create_table('event_marker',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('last_block_no', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.row_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('contract_id', name='uq_evtm')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_marker')
    op.drop_table('event')
    op.drop_table('contract')
    # ### end Alembic commands ###
