"""baseline

Revision ID: 2c36a28724f2
Revises: 
Create Date: 2022-08-30 16:24:12.363827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c36a28724f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('contract_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('abi', mysql.JSON(), nullable=False),
    sa.Column('contract_address', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('contract_creation_block_no', sa.Integer(), nullable=False),
    sa.Column('blocks_adjustment', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('contract_address', name='uq_ct')
    )
    op.create_table('event',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('contract_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('event_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('from_address', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('to_address', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=False),
    sa.Column('transaction_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('processed', mysql.BIT(), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_msg', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.row_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('transaction_hash', 'log_index', name='uq_evt')
    )
    op.create_table('event_marker',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('last_block_no', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.row_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('contract_id', name='uq_evtm')
    )
    op.create_table('registered_topics',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('arn', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.row_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('contract_id', 'arn', name='uq_rt')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registered_topics')
    op.drop_table('event_marker')
    op.drop_table('event')
    op.drop_table('contract')
    # ### end Alembic commands ###
