"""Update db model.

Revision ID: d2e6a765ef04
Revises: 2c108307d4c2
Create Date: 2022-05-27 18:09:51.343776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2e6a765ef04'
down_revision = '2c108307d4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_topics',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('arn', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.row_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('contract_id', 'arn', name='uq_rt')
    )
    conn = op.get_bind()
    conn.execute("""
        ALTER TABLE event 
            ADD COLUMN processed bit(1) NOT NULL DEFAULT b'0' AFTER log_index,
            ADD COLUMN error_code INT NOT NULL DEFAULT 0 AFTER processed,
            ADD COLUMN error_msg VARCHAR(512) NOT NULL DEFAULT "" AFTER error_code
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'processed')
    op.drop_column('event', 'error_msg')
    op.drop_column('event', 'error_code')
    op.drop_table('registered_topics')
    # ### end Alembic commands ###
